# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PiaSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PiaSample
  
  pod 'Fabric'
  pod 'Crashlytics'
  
  target 'PiaSampleTests' do
    inherit! :search_paths
  end

  target 'PiaSampleUITests' do
    inherit! :search_paths
  end

end
